theme = "oxidation"

[editor]
rulers = [80]
line-number = "relative"
color-modes = true

[editor.cursor-shape]
normal = 'block'
insert = 'bar'
select = 'underline'

[editor.file-picker]
hidden = false
